name: Test Path Configuration

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - 'modern/**'
      - '.github/workflows/test-paths.yml'

jobs:
  test-paths:
    name: Test Project Paths
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List project structure
        run: |
          echo "=== Project Root Structure ==="
          ls -la
          echo ""
          echo "=== Modern Directory ==="
          if [ -d "modern" ]; then
            ls -la modern/
            echo ""
            echo "=== Modern Backend ==="
            if [ -d "modern/backend" ]; then
              ls -la modern/backend/
            else
              echo "modern/backend not found!"
            fi
            echo ""
            echo "=== Modern Frontend ==="
            if [ -d "modern/frontend" ]; then
              ls -la modern/frontend/
            else
              echo "modern/frontend not found!"
            fi
          else
            echo "modern directory not found!"
          fi

      - name: Verify Go files
        run: |
          if [ -f "modern/backend/go.mod" ]; then
            echo "✅ go.mod found"
            cat modern/backend/go.mod
          else
            echo "❌ go.mod not found at modern/backend/go.mod"
          fi

      - name: Verify Python files
        run: |
          if [ -f "modern/frontend/main.py" ]; then
            echo "✅ main.py found"
            head -5 modern/frontend/main.py
          else
            echo "❌ main.py not found at modern/frontend/main.py"
          fi

          if [ -f "modern/frontend/requirements.txt" ]; then
            echo "✅ requirements.txt found"
            cat modern/frontend/requirements.txt
          else
            echo "❌ requirements.txt not found at modern/frontend/requirements.txt"
          fi

      - name: Test Go mod download path
        run: |
          if [ -d "modern/backend" ] && [ -f "modern/backend/go.mod" ]; then
            echo "✅ Path exists for Go operations"
            cd modern/backend
            pwd
            ls -la
          else
            echo "❌ Cannot navigate to modern/backend"
            exit 1
          fi

      - name: Legacy structure check
        run: |
          echo "=== Legacy Directory ==="
          if [ -d "legacy" ]; then
            ls -la legacy/
            if [ -d "legacy/updater" ]; then
              echo "✅ Legacy updater module found"
            else
              echo "❌ Legacy updater module not found"
            fi
          else
            echo "❌ legacy directory not found!"
          fi

      - name: Scripts directory check
        run: |
          echo "=== Scripts Directory ==="
          if [ -d "scripts" ]; then
            ls -la scripts/
          else
            echo "❌ scripts directory not found!"
          fi
